# Generated by Django 5.0.3 on 2024-05-13 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_delete_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'permissions': [('can_delete', 'Can delete!!!!')]},
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
